import os

BASE_DIR = "."
TEMPLATE = """# {project_name}

## 📌 Project Overview
This project is part of the **Machine Learning Projects Collection (100+ projects with source code)**.  

## 🛠️ Potential Technologies / Tools
- Python
- Pandas
- Scikit-learn
- TensorFlow/Keras (if deep learning)

## 🚀 How to Run
1. Clone this repository
2. Navigate to this project folder
3. Install dependencies (`pip install -r requirements.txt`)
4. Run the code  

---
✅ Auto-generated by [ML Projects Bot] 🤖
"""

def format_name(folder):
    return folder.replace("-", " ").replace("_", " ").title()

for folder in os.listdir(BASE_DIR):
    if os.path.isdir(folder) and folder not in [".github", ".git"]:
        readme_path = os.path.join(folder, "README.md")
        if not os.path.exists(readme_path):
            project_name = format_name(folder)
            with open(readme_path, "w") as f:
                f.write(TEMPLATE.format(project_name=project_name))
            print(f"Generated README for {project_name}")
